title: Arthur Robertson
author: Arthur Robertson
subtitle: Blog

url: "https://athrur.github.io"

footer: true
footer_url: "https://github.com/athrur/athrur.github.io"
footer_text: "Website Source Code"

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Contact"
   absolute-link: "https://linkedin.com/in/arthur-robertson"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  
webmaster_verifications:
  google: "s3E22yr28L3Lhs8ZdJ34k6Rcolu_3VNLJoqAuPl"
  
title: Arthur Robertson
tagline: My blog and personal website.
description: My personal website and blog about my interests and projects.
author:
  name: Arthur Robertson
  url: https://athrur.github.io/